### ISSUE TITLE
Track new Progress APIs

### ISSUE THREAD

**Issue by jamamp** [Jman012/FloatplaneAPI#3]
Most detail from AJ in Discord. Tracking here for documentation.

URL for posting progress: https://www.floatplane.com/api/v3/content/progress

```js
/**
   * @api {post} /content/progress
   * @apiPrefix /api
   * @apiName updateProgress
   * @apiFunction updateProgress
   * @apiGroup Content
   * @apiDescription updates Playback Progress
   *
   * @apiParam {string} id
   * @apiParam {string} contentType
   * @apiParam {number} progress
   *
   * @apiReturns {void}
   *
   * @apiError contentNotFoundError - No such content could be found.
   * @apiError paramValidationError - "id" is required
   * @apiError paramValidationError - "contentType" is required
   * @apiError notLoggedInError - You must be logged-in to access this resource.
   */
```

> contentType, in your case, should be "video" or "audio" depending on what you're playing. And, "id" is the content ID, so the video, audio ID that the blogpost returns

> Please keep this endpoint to a max of 10RPM, or update for each ~10 seconds of playback If you can, I would only update on player exit.

The request to get progress is : `POST https://www.floatplane.com/api/v3/content/get/progress`
Body : 
```json
{"ids":["VVHQaTtSc7","hjfJHy9cUj","GZRmozSIM0","fvNbFlmoPj","15KcPBNX6E","oK260WpGEI","ihZAAx8HXR","jhmLqBaFuJ","MTTtJArRsw","bll7niF3ch","apxTRWH7Xe","PcQixIYJ7P","oYURYNHuub","WMx2Uj1PA4","K6T6tX85WD","cfZTUxS5Ky","P1u086uk9E","i74rOKGFEG","xyjPflHtpu","QGutu0g41u"],"contentType":"blogPost"}
```

However, there is a new `progress` field that appears when set on a video object (`/api/v3/content/video?id=zpk4mwdZTA`) as well. The above bulk query is needed for showing progress on a home page before querying the `/api/v3/content/video` object for playback (at which point the current progress isn't too important since playback will begin and will be updated soon). I will add in the new `progress` field (not required, and not nullable, always an integer).

Make sure it's video/audio IDs, not blogPostId.

**Comment by jamamp** [comment]
For POSTing progress:

POST https://www.floatplane.com/api/v3/content/progress

```json
{
  "id": "zpk4mwdZTA",
  "contentType": "video",
  "progress": null
}
```

**Comment by NickM-27** [comment]
I'm noticing the `progress` values returned by `POST https://www.floatplane.com/api/v3/content/get/progress` are entirely different (and incorrect) from those that are returned along with the video-info (which is correct). Am I interpreting the bulk API incorrectly or what does it mean?

**Comment by NickM-27** [comment]
Looks like the bulk API is in % but the set/individual values are in seconds

**Comment by jamamp** [comment]
Looks like Floatplane updated with some progress code added.

Findings:
- Limit 50 IDs per request.
- When submitting progress, the `progress` field is indeed seconds, not percentage.
- Submitting a progress of `0` (which the FP website does when first visiting the video) may result in an HTTP 400 "unknownError"
- FP submits progress on the web socket. HTTP endpoints should be available as a fallback for TV apps that don't have sockets yet.
- FP sends progress on play/pause.
- Audio attachments get progress as well.
